<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EscolasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('escolas')->delete();
        
        \DB::table('escolas')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nome' => 'Adolfina Leonor Soares Dos Santos',
                'cie' => 402862,
                'regiao' => 'Centro',
                'bairro' => 'Sumare',
                'endereco' => 'Av. Siqueira Campos',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38812521',
                'email' => 'emefadolfinacaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            1 => 
            array (
                'id' => 2,
                'nome' => 'Adriana Aparecida Cassiano',
                'cie' => 5420,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'R. Sao Roque',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38871449',
                'email' => 'cei.adrianacassiano@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            2 => 
            array (
                'id' => 3,
                'nome' => 'Aida de Almeida Castro Grazioli',
                'cie' => 225940,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'endereco' => 'Rua Francisco Ribeiro',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38822610',
                'email' => 'emefgraziolicaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            3 => 
            array (
                'id' => 4,
                'nome' => 'Alaor Xavier Junqueira',
                'cie' => 223098,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Rua Jose Ferreira Dos Santos',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38872612',
                'email' => 'emefjunqueiracaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            4 => 
            array (
                'id' => 5,
                'nome' => 'Antonia Antunes Arouca',
                'cie' => 225939,
                'regiao' => 'Norte',
                'bairro' => 'Massagassu',
                'endereco' => 'Rua Italia Baffi Magni',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38843900',
                'email' => 'emefaroucacaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            5 => 
            array (
                'id' => 6,
                'nome' => 'Antonia Ribeiro Da Silva',
                'cie' => 243449,
                'regiao' => 'Centro',
                'bairro' => 'Jardim California',
                'endereco' => 'Av. Cidade Alves Pereira',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38822286',
                'email' => 'ciefiribeiro@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            6 => 
            array (
                'id' => 7,
                'nome' => 'Antonio De Freitas Avelar',
                'cie' => 447785,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'endereco' => 'Rua Joao Marcelo',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38822493',
                'email' => 'emefavelarcaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            7 => 
            array (
                'id' => 8,
                'nome' => 'Aparecida Maria Pires De Meneses',
                'cie' => 2033,
                'regiao' => 'Norte',
                'bairro' => 'Olaria',
                'endereco' => 'Av. Marginal Ipiranga',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38838988',
                'email' => 'crecheolaria@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            8 => 
            array (
                'id' => 9,
                'nome' => 'Benedito Inacio Soares',
                'cie' => 208334,
                'regiao' => 'Norte',
                'bairro' => 'Massagassu',
                'endereco' => 'Av Regina Margareth Passos',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38842450',
                'email' => 'emefsoarescaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            9 => 
            array (
                'id' => 10,
                'nome' => 'Bernardo Ferreira Louzada',
                'cie' => 208346,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'endereco' => 'Rua Horto Florestal',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38822221',
                'email' => 'emeflouzadacaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            10 => 
            array (
                'id' => 11,
                'nome' => 'Carlos Altero Ortega',
                'cie' => 225952,
                'regiao' => 'Sul',
                'bairro' => 'Morro Do Algodao',
                'endereco' => 'Rua Sete',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38873021',
                'email' => 'emefortegacaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            11 => 
            array (
                'id' => 12,
                'nome' => 'Carlos De Almeida Rodrigues Dr.',
                'cie' => 215077,
                'regiao' => 'Centro',
                'bairro' => 'Indaia',
                'endereco' => 'Av. Pernambuco',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38824679',
                'email' => 'emefrodriguescaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            12 => 
            array (
                'id' => 13,
                'nome' => 'CEI do Bairro Poiares',
                'cie' => 422423,
                'regiao' => 'Centro',
                'bairro' => 'Poiares',
                'endereco' => 'Av. Marechal Floriano Peixoto',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38876315',
                'email' => 'cepoiares@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            13 => 
            array (
                'id' => 14,
                'nome' => 'Celia Rocha Lobo',
                'cie' => 279626,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Rua Benedito Jacinto Do Prado',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38883311',
                'email' => 'cei.celialobo@caraguatatuba.sp.org.br',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            14 => 
            array (
                'id' => 15,
                'nome' => 'Creche Santo Antonio',
                'cie' => 300603,
                'regiao' => 'Sul',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Elvira Perpetua De Santana',
                'observacao' => 'Particular',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38873304',
                'email' => 'criancaa@uol.com.br',
                'tipo_ensino' => 'CEI',
            ),
            15 => 
            array (
                'id' => 16,
                'nome' => 'Edna Maria Nogueira Ferraz',
                'cie' => 6288,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Rua Benedito Fortunato',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38873014',
                'email' => 'emefednaferrazcaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            16 => 
            array (
                'id' => 17,
                'nome' => 'Elisa Butschkau',
                'cie' => 273314,
                'regiao' => 'Sul',
                'bairro' => 'Barranco Alto',
                'endereco' => 'Avenida Manoel de Castro',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38871016',
                'email' => 'ceielisabutschkau@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            17 => 
            array (
                'id' => 18,
                'nome' => 'Ester Nunes De Souza',
                'cie' => 499559,
                'regiao' => 'Norte',
                'bairro' => 'Sertao Dos Tourinhos',
                'endereco' => 'Rua Manoel Francisco Ricardo',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38841655',
                'email' => 'ceinunescaraguatatuba@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            18 => 
            array (
                'id' => 19,
                'nome' => 'Euclydes Ferreira',
                'cie' => 499560,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Av. Jose Geraldo Fernandes Da Silva Filho',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38851802',
                'email' => 'emefeuclydesferreira@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            19 => 
            array (
                'id' => 20,
                'nome' => 'Francisco Assis De Carvalho',
                'cie' => 225988,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Av. Jose Geraldo Fernandes Da Silva Filho',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38851801',
                'email' => 'ceifranciscoassisdecarvalho@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            20 => 
            array (
                'id' => 21,
                'nome' => 'Geraldo De Lima',
                'cie' => 273302,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'Av. Pedro Goncalves',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38874322',
                'email' => 'emeflimacaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            21 => 
            array (
                'id' => 22,
                'nome' => 'Honorina Pacheco Correa',
                'cie' => 5336,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'endereco' => 'Av. Americo Thimoteo Do Rosario',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38835577',
                'email' => 'cei.riodoouro@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            22 => 
            array (
                'id' => 23,
                'nome' => 'Jane Urbano Focesi',
                'cie' => 215089,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'R. Sao Roque',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38871514',
                'email' => 'emefjanefocesi@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            23 => 
            array (
                'id' => 24,
                'nome' => 'Joao Baptista Gardelin',
                'cie' => 200359,
                'regiao' => 'Centro',
                'bairro' => 'Poiares',
                'endereco' => 'Rua Joaquim Jose Da Silva Xavier',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38873101',
                'email' => 'emefgardelincaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            24 => 
            array (
                'id' => 25,
                'nome' => 'Joao Benedito Marcondes',
                'cie' => 383636,
                'regiao' => 'Sul',
                'bairro' => 'Baranco Alto',
                'endereco' => 'Rua Benedito Severino De Castro',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38874291',
                'email' => 'emefmarcondescaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            25 => 
            array (
                'id' => 26,
                'nome' => 'Joao Lino Da Cruz',
                'cie' => 208358,
                'regiao' => 'Sul',
                'bairro' => 'Baranco Alto',
                'endereco' => 'Rua Luiz Jacinto Da Silva',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38882865',
                'email' => 'cei.joaocruz@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            26 => 
            array (
                'id' => 27,
                'nome' => 'Joao Thimoteo Do Rosario',
                'cie' => 225997,
                'regiao' => 'Norte',
                'bairro' => 'Cantagalo',
                'endereco' => 'Estrada Do Cantagalo',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38890278',
                'email' => 'emefrosariocaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            27 => 
            array (
                'id' => 28,
                'nome' => 'Jorge Passos',
                'cie' => 22226,
                'regiao' => 'Centro',
                'bairro' => 'Jaraguazinho',
                'endereco' => 'Rua Oziel Egidio De Faria',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38824395',
                'email' => 'emefpassoscaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            28 => 
            array (
                'id' => 29,
                'nome' => 'Leonor Mendes De Barros',
                'cie' => 222324,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Rua Joao Carlos Balio',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38876108',
                'email' => 'ceileonor.travessao@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            29 => 
            array (
                'id' => 30,
                'nome' => 'Lucio Jacinto Dos Santos',
                'cie' => 243450,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Denilza Sebastiana Santos',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38834533',
                'email' => 'emefsantoscaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            30 => 
            array (
                'id' => 31,
                'nome' => 'Luiz Ribeiro Muniz',
                'cie' => 565817,
                'regiao' => 'Centro',
                'bairro' => 'Martim De Sa',
                'endereco' => 'Rua Analandia',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38825698',
                'email' => 'emefmunizcaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            31 => 
            array (
                'id' => 32,
                'nome' => 'Luiz Silvar Do Prado',
                'cie' => 495037,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38869931',
                'email' => 'emef.luizsilvar@caraguatatuba.sp.gov.br',
                'tipo_ensino' => 'EMEF',
            ),
            32 => 
            array (
                'id' => 33,
                'nome' => 'Maria Aparecida De Carvalho',
                'cie' => 225903,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Av. Marechal Deodoro Da Fonseca',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38862050',
                'email' => 'emefmariacarvalhocaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            33 => 
            array (
                'id' => 34,
                'nome' => 'Maria Aparecida Ujio',
                'cie' => 22299,
                'regiao' => 'Sul',
                'bairro' => 'Porto Novo',
                'endereco' => 'Av. Ezequiel Da Silva Barreto',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38873836',
                'email' => 'ujiomariaaparecida@yahoo.com.br',
                'tipo_ensino' => 'EMEF',
            ),
            34 => 
            array (
                'id' => 35,
                'nome' => 'Maria Carlita Saraiva Guedes',
                'cie' => 201777,
                'regiao' => 'Sul',
                'bairro' => 'Morro Do Algodao',
                'endereco' => 'Travessa Cinco',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38883223',
                'email' => 'cei.mariacarlita@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            35 => 
            array (
                'id' => 36,
                'nome' => 'Maria De Lourdes Lucarelli Perez',
                'cie' => 495025,
                'regiao' => 'Centro',
                'bairro' => 'Indaia',
                'endereco' => 'Av. Santa Catarina',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38877822',
                'email' => 'emeiperezcaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI',
            ),
            36 => 
            array (
                'id' => 37,
                'nome' => 'Maria Elma Mansano',
                'cie' => 565748,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Av. Marechal Deodoro Da Fonseca',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38862054',
                'email' => 'ceimansano@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            37 => 
            array (
                'id' => 38,
                'nome' => 'Maria Eugenia Aranha Chodounsky',
                'cie' => 435879,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38869932',
                'email' => 'ceiemeimariaeugenia@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            38 => 
            array (
                'id' => 39,
                'nome' => 'Maria Moraes De Oliveira',
                'cie' => 569537,
                'regiao' => 'Centro',
                'bairro' => 'Jardim Gaivotas',
                'endereco' => 'Rua Pica Pau',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38877462',
                'email' => 'emefgaivotascaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            39 => 
            array (
                'id' => 40,
                'nome' => 'Maria Onicie Dias Pereira',
                'cie' => 225976,
                'regiao' => 'Centro',
                'bairro' => 'Jaraguazinho',
                'endereco' => 'Rua Jose Neder',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38878087',
                'email' => 'cei.mariaonicie@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            40 => 
            array (
                'id' => 41,
                'nome' => 'Maria Thereza De Souza Castro',
                'cie' => 208361,
                'regiao' => 'Norte',
                'bairro' => 'Getuba',
                'endereco' => 'Rua Seishi Yoshimoto',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38842921',
                'email' => 'emefcastrocaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            41 => 
            array (
                'id' => 42,
                'nome' => 'Masako Sone',
                'cie' => 810642,
                'regiao' => 'Sul',
                'bairro' => 'Pegorelli',
                'endereco' => 'Rua Abra De Dentro',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38872444',
                'email' => 'emefsonecaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            42 => 
            array (
                'id' => 43,
                'nome' => 'Meimei',
                'cie' => 273351,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Odete Machado Pinto',
                'observacao' => 'Particular',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38834648',
                'email' => 'cmeimei250@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            43 => 
            array (
                'id' => 44,
                'nome' => 'Messias Mendes De Souza',
                'cie' => 225964,
                'regiao' => 'Centro',
                'bairro' => 'Ipiranga',
                'endereco' => 'Av. Brasil',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38839788',
                'email' => 'ceiemeimessiasipiranga@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            44 => 
            array (
                'id' => 45,
                'nome' => 'Oswaldo Ferreira',
                'cie' => 226002,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38821067',
                'email' => 'emefferreiracaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            45 => 
            array (
                'id' => 46,
                'nome' => 'Pedro Joao De Oliveira',
                'cie' => 78086,
                'regiao' => 'Norte',
                'bairro' => 'Tabatinga',
                'endereco' => 'Rua Benedito Serrado',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38842091',
                'email' => 'emefoliveiracaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI/EMEF',
            ),
            46 => 
            array (
                'id' => 47,
                'nome' => 'Regina Celia Santos Chapira Blaustein',
                'cie' => 375172,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Rua Jacupiranga',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38876422',
                'email' => 'ceiregina.travessao@gmail.com',
                'tipo_ensino' => 'CEI',
            ),
            47 => 
            array (
                'id' => 48,
                'nome' => 'Ricardo Luques Sammarco Serra',
                'cie' => 78074,
                'regiao' => 'Sul',
                'bairro' => 'Praia Das Palmeiras',
                'endereco' => 'Rua Aldo Marcucci',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38884186',
                'email' => 'emefserracaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEF',
            ),
            48 => 
            array (
                'id' => 49,
                'nome' => 'Santina Nardi Marques',
                'cie' => 435983,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'endereco' => 'Rua Antonio Nardi',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38833477',
                'email' => 'ceisantinanardicaraguatatuba@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            49 => 
            array (
                'id' => 50,
                'nome' => 'Severino Vitoriano Dos Santos',
                'cie' => 807679,
                'regiao' => 'Centro',
                'bairro' => 'Jardim Das Gaivotas',
                'endereco' => 'Av. Cardeal',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38873047',
                'email' => 'ceigaivotas@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            50 => 
            array (
                'id' => 51,
                'nome' => 'Telma Do Amarante Veiga Santos',
                'cie' => 442628,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'endereco' => 'Rua Antonio Dos Santos',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38826090',
                'email' => 'cei.telmaveiga@caraguatatuba.sp.gov.br',
                'tipo_ensino' => 'CEI',
            ),
            51 => 
            array (
                'id' => 52,
                'nome' => 'Thereza Yanesse Schmidt Cardozo',
                'cie' => 451861,
                'regiao' => 'Sul',
                'bairro' => 'Porto Novo',
                'endereco' => 'Av. Ezequiel Da Silva Barreto',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38871565',
                'email' => 'ceiportonovo.caragua@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            52 => 
            array (
                'id' => 53,
                'nome' => 'Vera Da Silva Santos',
                'cie' => 5780,
                'regiao' => 'Norte',
                'bairro' => 'Getuba',
                'endereco' => 'Av. Azaleias',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38893535',
                'email' => 'cemeifazendinha@gmail.com',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            53 => 
            array (
                'id' => 54,
                'nome' => 'Yasutada Nasu',
                'cie' => 212489,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'endereco' => 'R. Pedro Goncalves Leite',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38874322',
                'email' => 'emeiyasutadacaraguatatuba@gmail.com',
                'tipo_ensino' => 'EMEI',
            ),
            54 => 
            array (
                'id' => 55,
                'nome' => 'Seduc',
                'cie' => 1,
                'regiao' => 'Norte',
                'bairro' => 'Indaiá',
                'endereco' => 'Av. Rio de Janeiro 860',
                'observacao' => 'Sem observações',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38977027',
                'email' => 'informatica.educativa@caraguatatuba.sp.gov.br',
                'tipo_ensino' => 'SECRETARIA',
            ),
            55 => 
            array (
                'id' => 56,
                'nome' => 'Stela da Silva',
                'cie' => 9028,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => ' Rua João Carlos Balio, 355',
                'observacao' => 'Sem observações.',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38977000',
                'email' => 'cei.stelasilva@caraguatatuba.sp.gov.br',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            56 => 
            array (
                'id' => 57,
                'nome' => 'Waldete Ferreira de Souza',
                'cie' => 9034,
                'regiao' => 'Sul',
                'bairro' => 'Pegorelli',
                'endereco' => 'R. Circular, 10',
                'observacao' => 'Sem observações.',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38977000',
                'email' => 'cei.waldete.souza@educacaocaraguatatuba.com.br',
                'tipo_ensino' => 'CEI/EMEI',
            ),
            57 => 
            array (
                'id' => 58,
                'nome' => 'Debora Valle da Silva Pilon',
                'cie' => 8982,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'endereco' => 'Av. José da Costa Pinheiro Júnior, 422',
                'observacao' => 'Sem observações.',
                'created_at' => '2022-02-07 00:00:00',
                'updated_at' => '2022-02-07 00:00:00',
            'telefone' => '(12) 38977000',
                'email' => 'emef.deborapilon@caraguatatuba.sp.gov.br',
                'tipo_ensino' => 'EMEF',
            ),
        ));
        
        
    }
}